'use strict';const test=require('node:test');const assert=require('node:assert/strict');const R=require('../domain/revenuePolicy');const {readiness,requireProviders}=require('../services/providerBoundary');
const {evaluateCloseReadiness}=require('../services/closeReadiness');
function contract(overrides={}){return{tenantId:'t1',contractId:'C-1',version:'v2',framework:'ASC606',currency:'USD',effectiveFrom:'2026-01-01',ruleVersion:'asc606-2026.1',fixedConsiderationMinor:100000,variableConsideration:{estimateMinor:20000,constraintMinor:10000,method:'expected_value'},obligations:[{id:'license',standaloneSellingPriceMinor:60000,satisfactionMethod:'point_in_time',evidenceRef:'memo-1'},{id:'support',standaloneSellingPriceMinor:40000,satisfactionMethod:'over_time',evidenceRef:'memo-2'}],...overrides};}
function events(){return[{eventId:'e1',obligationId:'license',type:'satisfied',occurredAt:'2026-01-10T00:00:00Z',receivedAt:'2026-01-10T01:00:00Z',sourceDigest:'a'.repeat(64)},{eventId:'e2',obligationId:'support',type:'progress',progressBasisPoints:5000,occurredAt:'2026-06-30T00:00:00Z',receivedAt:'2026-06-30T01:00:00Z',sourceDigest:'b'.repeat(64)}];}
test('validates ASC 606 and IFRS 15 contract versions and obligations',()=>{assert.equal(R.validateContract(contract()).ok,true);const bad=contract({framework:'invented'});bad.obligations[0].standaloneSellingPriceMinor=0;const r=R.validateContract(bad);assert.equal(r.ok,false);assert.equal(r.errors.length,2);});
test('constrains variable consideration and allocates by relative SSP exactly',()=>{const a=R.allocateTransactionPrice(contract());assert.equal(a.transactionPriceMinor,110000);assert.deepEqual(a.allocations.map(x=>x.amountMinor),[66000,44000]);assert.equal(a.allocations.reduce((s,x)=>s+x.amountMinor,0),110000);assert.match(a.allocationDigest,/^[a-f0-9]{64}$/);});
test('recognizes point-in-time and over-time satisfaction with traceable events',()=>{const s=R.recognize(contract(),events());assert.equal(s.totals.recognizedMinor,88000);assert.equal(s.totals.deferredMinor,22000);assert.equal(s.lines[0].eventId,'e1');assert.match(s.scheduleDigest,/^[a-f0-9]{64}$/);});
test('usage-based obligations require a cumulative usage progress event',()=>{const c=contract();c.obligations[1].satisfactionMethod='usage_based';const s=R.recognize(c,events());assert.equal(s.lines.find(x=>x.obligationId==='support').currentRecognizedMinor,22000);const invalid=events();delete invalid[1].progressBasisPoints;assert.throws(()=>R.recognize(c,invalid),/progress basis points/);});
test('progress regression requires a reversal or restatement',()=>{assert.throws(()=>R.recognize(contract(),events(),{support:30000}),/progress regressed/);});
test('classifies standalone distinct modifications prospectively and other amendments as catch-up',()=>{const a={amendmentId:'A1',version:'v1',priceDeltaMinor:10000,sourceDigest:'c'.repeat(64),addsDistinctGoods:true,pricedAtStandaloneSellingPrice:true};assert.equal(R.assessModification(contract(),a).treatment,'prospective_separate_contract');assert.equal(R.assessModification(contract(),{...a,pricedAtStandaloneSellingPrice:false}).treatment,'cumulative_catch_up');});
test('credits are immutable linked negative schedules and balanced reversal journals',()=>{const schedule=R.recognize(contract(),events()),credit=R.applyCredit(schedule,{creditId:'CR-1',amountMinor:5000,occurredAt:'2026-07-01T00:00:00Z',sourceDigest:'d'.repeat(64)});assert.equal(credit.totals.recognizedMinor,-5000);const j=R.proposeJournal(credit,{id:'2026-07',start:'2026-07-01',end:'2026-07-31'});assert.equal(j.balanced,true);assert.equal(j.lines[0].account,'revenue');assert.equal(j.debitMinor,5000);});
test('converts FX with a versioned authoritative rate and keeps journal evidence',()=>{const fx={version:'fx-2026-06-30',unitsPerMillion:1250000,sourceDigest:'e'.repeat(64),effectiveAt:'2026-06-30T23:59:00Z',baseCurrency:'USD'};assert.equal(R.convertFx(10000,fx).baseAmountMinor,12500);const j=R.proposeJournal(R.recognize(contract(),events()),{id:'p1',start:'2026-01-01',end:'2026-06-30'},fx);assert.equal(j.debitMinor,110000);assert.equal(j.creditMinor,110000);});
test('late events replay locked history into an open-period restatement',()=>{const late=[events()[0],{...events()[1],occurredAt:'2026-06-30T00:00:00Z',receivedAt:'2026-07-05T00:00:00Z'}];const r=R.replayLateEvents(contract(),late,'2026-06-30T23:59:59Z','2026-07');assert.deepEqual(r.lateEventIds,['e2']);assert.equal(r.restatementDeltaMinor,22000);assert.equal(r.restatementRequired,true);});
test('journals remain balanced and explain their rule/schedule evidence',()=>{const j=R.proposeJournal(R.recognize(contract(),events()),{id:'2026-H1',start:'2026-01-01',end:'2026-06-30'});assert.equal(j.balanced,true);assert.equal(j.debitMinor,88000);assert.equal(j.creditMinor,88000);assert.match(j.journalDigest,/^[a-f0-9]{64}$/);});
test('segregates preparer, controller, posting operator, and auditor',()=>{const approvals=[{actorId:2,decision:'approve'}];assert.equal(R.authorize({current:'review_pending',next:'approved',actor:{role:'controller'},createdBy:1,approvals}).ok,true);assert.equal(R.authorize({current:'review_pending',next:'approved',actor:{role:'controller'},createdBy:2,approvals}).ok,false);assert.equal(R.authorize({current:'posting_pending',next:'posted',actor:{role:'posting_operator'}}).ok,true);assert.equal(R.authorize({current:'reconciled',next:'locked',actor:{role:'auditor'}}).ok,true);});
test('locked periods allow only linked reversals and restatements',()=>{assert.equal(R.authorize({current:'reconciled',next:'locked',actor:{role:'auditor'},periodLocked:true}).ok,false);assert.equal(R.authorize({current:'locked',next:'restated',actor:{role:'revrec_accountant'},periodLocked:true}).ok,true);});
test('posting and reconciliation fail closed without providers and matched evidence',()=>{assert.equal(R.authorize({current:'approved',next:'posting_pending',actor:{role:'revrec_accountant'},providers:['erp']}).ok,false);assert.equal(R.authorize({current:'approved',next:'posting_pending',actor:{role:'revrec_accountant'},providers:['erp','general_ledger']}).ok,true);assert.equal(R.authorize({current:'posted',next:'reconciled',actor:{role:'auditor'},reconciled:false}).ok,false);});
test('provider boundary requires authoritative CRM contract billing ERP usage GL and FX adapters',()=>{assert.equal(readiness({}).ready,false);assert.throws(()=>requireProviders(['erp','general_ledger'],{}),/not ready/);const env={};for(const n of ['CRM','CONTRACTS','BILLING','ERP','USAGE','GENERAL_LEDGER','FX']){env[`${n}_PROVIDER_ENABLED`]='true';env[`${n}_PROVIDER_URL`]=`https://${n.toLowerCase()}.example.invalid`;env[`${n}_PROVIDER_TOKEN`]='runtime';}assert.equal(readiness(env).ready,true);});
test('golden replay covers variable consideration, bundles, renewals, credits, modifications, FX, usage, and close replay',()=>{const scenarios=['variable_consideration','bundle','renewal','modification','usage_based'];const cases=scenarios.map((scenario,i)=>({caseId:`c${i}`,scenario,contract:contract({version:scenario==='renewal'?'renewal-v1':'v2'}),events:events(),expectedRecognizedMinor:88000}));cases.push({caseId:'credit',scenario:'credit',contract:contract(),events:events(),credit:{creditId:'cr',amountMinor:5000,occurredAt:'2026-07-01T00:00:00Z',sourceDigest:'f'.repeat(64)},expectedRecognizedMinor:-5000});cases.push({caseId:'fx',scenario:'fx',contract:contract(),events:events(),fxRate:{version:'fx1',unitsPerMillion:1250000,sourceDigest:'e'.repeat(64),effectiveAt:'2026-06-30T00:00:00Z'},expectedRecognizedMinor:110000});cases.push({caseId:'replay',scenario:'period_close_replay',contract:contract(),events:[events()[0],{...events()[1],receivedAt:'2026-07-05T00:00:00Z'}],lockedThrough:'2026-06-30T23:59:59Z',openPeriodId:'2026-07',expectedRecognizedMinor:22000});const result=R.evaluateGolden(cases);assert.equal(result.passed,true);assert.equal(Object.values(result.coverage).every(Boolean),true);});
test('month-end readiness explains blockers and never locks a period',()=>{const blocked=evaluateCloseReadiness({periodRef:'2026-08',sourceSyncs:[{reconciled:false}],journals:[{state:'approved'}],postingOutbox:[{status:'retry'}],reconciliations:[{matched:false}],goldenResults:[]});assert.equal(blocked.readyForControllerReview,false);assert.equal(blocked.blockers.length,5);const ready=evaluateCloseReadiness({periodRef:'2026-08',sourceSyncs:[{reconciled:true}],journals:[{state:'reconciled'}],postingOutbox:[{status:'delivered'}],reconciliations:[{matched:true}],goldenResults:[{passed:true}]});assert.equal(ready.readyForControllerReview,true);assert.equal(ready.automaticPeriodLock,false);});
